esphome:
  name: heat-controller
  friendly_name: "Heat Controller"

esp8266:
  board: esp12e

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: <your api key>

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # I feel better with static IPs, delete entry if not desired
  manual_ip:
    static_ip: <device ip>
    gateway: <your gateway>
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "HeatController"
    password: <your password>

captive_portal:

# Status LED
status_led:
  pin:
    number: GPIO
    inverted: true

# 1-wire config
dallas:
  - pin: GPIO16

# Relais config
switch:
  - platform: gpio
    pin:
      number: GPIO4
    id: heater_relay_1
    name: "Heater Relay CH1"
  - platform: gpio
    pin:
      number: GPIO5
    id: heater_relay_2
    name: "Heater Relay CH2"

# DS18B20 sensors
sensor:
  - platform: uptime
    name: "HeatController Uptime"
  - platform: wifi_signal
    name: "HeatController WiFi Signal"
    update_interval: 60s
  - platform: dallas
    address: <uid of DS18B20, end with ...aa28>
    id: heater_sensor_1
    name: "Heater Sensor CH1"
  - platform: dallas
    address: <uid of DS18B20, end with ...aa28>
    id: heater_sensor_2
    name: "Heater Sensor CH2"
  # Optional sensors
  - platform: dallas
    address: <uid of DS18B20, end with ...aa28>
    id: environment_sensor
    name: "Environment Sensor"

# Controller
climate:
  - platform: bang_bang
    name: "Controller CH1"
    sensor: heater_sensor_1
    default_target_temperature_low: 20 째C
    default_target_temperature_high: 25 째C
    heat_action:
      - switch.turn_on: heater_relay_1
    idle_action:
      - switch.turn_off: heater_relay_1
  - platform: bang_bang
    name: "Controller CH2"
    sensor: heater_sensor_2
    default_target_temperature_low: 20 째C
    default_target_temperature_high: 25 째C
    heat_action:
      - switch.turn_on: heater_relay_2
    idle_action:
      - switch.turn_off: heater_relay_2
