esphome:
  name: heat-controller
  friendly_name: "Heat Controller"

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: <your api key>

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: <device ip>
    gateway: <your gateway>
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "HeatController"
    password: <your password>

captive_portal:


# 1-wire config
dallas:
  - pin: D5

# Relais config
switch:
  - platform: gpio
    pin:
      number: D4
      inverted: true
    id: heater_relay_1
    name: "Heater Relay CH1"
  - platform: gpio
    pin:
      number: D3
      inverted: true
    id: heater_relay_2
    name: "Heater Relay CH2"

# DS18B20 Sensors
sensor:
  - platform: dallas
    address: 0x<uid of DS18B20>aa28
    id: frost_sensor_1
    name: "Frost Sensor 1"
  - platform: dallas
    address: 0x<uid of DS18B20>aa28
    id: frost_sensor_2
    name: "Frost Sensor 2"

# Controller
climate:
  - platform: bang_bang
    name: "Regler Kanal 1"
    sensor: frost_sensor_1
    default_target_temperature_low: 0 째C
    default_target_temperature_high: 5 째C
    heat_action:
      - switch.turn_on: heater_relay_1
    idle_action:
      - switch.turn_off: heater_relay_1
  - platform: bang_bang
    name: "Regler Kanal 2"
    sensor: frost_sensor_2
    default_target_temperature_low: 0 째C
    default_target_temperature_high: 5 째C
    heat_action:
      - switch.turn_on: heater_relay_2
    idle_action:
      - switch.turn_off: heater_relay_2
